version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6370:6370"
    volumes:
      - "redis_data:/data"

  app:
    build: "./app"
    ports:
      - "8080:8080"
    environment:
      DB_HOST: cluster0.egtnh.mongodb.net/user
      DB_USER: admin
      DB_PASSWORD: nBA4MXm74LLN4gYm
      TYPETALK_CLIENT_ID: nb0Op8DgmHj6cA3dKl0R0loC3W0rlskD
      TYPETALK_CLIENT_SECRET: pyaOD5EhA73WIFXsOhfmFuxO3Ewxl7viqqkZSipNXZpliL2NWcwdQtFJgyGRg2L4
      VALANCE: 1
    depends_on:
      - redis
    tty: true
volumes:
  redis_data:
