version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6370"
    volumes:
      - "./data/redis:/data"

  app:
    build: "./app"
    ports:
      - "8080:8080"
    environment:
      DB_HOST: cluster0.egtnh.mongodb.net/user
      DB_USER: admin
      DB_PASSWORD: nBA4MXm74LLN4gYm
      TYPETALK_CLIENT_ID: nb0Op8DgmHj6cA3dKl0R0loC3W0rlskD
      TYPETALK_CLIENT_SECRET: pyaOD5EhA73WIFXsOhfmFuxO3Ewxl7viqqkZSipNXZpliL2NWcwdQtFJgyGRg2L4
      VALANCE: 1
    restart: always
    depends_on:
      - redis

  caddy:
    image: caddy:latest
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/caddy_data"
    environment:
      HOSTNAME: os3-359-12725.vs.sakura.ne.jp
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy_data:
    driver: "local"
