version: "3"
services:
  app:
    restart: always
    build: "./bot"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: cluster0.egtnh.mongodb.net/user
      DB_USER: admin
      DB_PASSWORD: nBA4MXm74LLN4gYm
      TYPETALK_CLIENT_ID: nb0Op8DgmHj6cA3dKl0R0loC3W0rlskD
      TYPETALK_CLIENT_SECRET: pyaOD5EhA73WIFXsOhfmFuxO3Ewxl7viqqkZSipNXZpliL2NWcwdQtFJgyGRg2L4
      VALANCE: 1
    tty: true
volumes:
  redis_data:
